In [1]:
import numpy as np
import pandas as pd

#libs for ML regression model
from sklearn.linear_model import LogisticRegression
from sklearn import metrics  
from sklearn.metrics import roc_curve, roc_auc_score

#libs for plotting
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

#exporting ML model
import joblib

#lib to download dataset on g drive


#setting display option max rows
#pd.options.display.max_rows = None

#importing custom-made functions
import sys #importing local functions in src folder
sys.path.append('../src/')
from utils import *

In [2]:
inputs_train = pd.read_csv ('loan_data_inputs_train.csv',index_col =0)
targets_train = pd.read_csv ('loan_data_targets_train.csv',index_col =0)
inputs_test = pd.read_csv ('loan_data_inputs_test.csv',index_col =0)
targets_test = pd.read_csv ('loan_data_targets_test.csv',index_col =0)

### Exploring data

In [3]:
targets_train.value_counts()

good_bad
1           332966
0            40062
Name: count, dtype: int64

In [4]:
inputs_train.shape

(373028, 313)

In [5]:
inputs_train.columns.values

<StringArray>
[                    'Unnamed: 0',                             'id',
                      'member_id',                      'loan_amnt',
                    'funded_amnt',                'funded_amnt_inv',
                           'term',                       'int_rate',
                    'installment',                          'grade',
 ...
                  'dti:21.7-22.4',                    'dti:22.4-35',
                        'dti:>35', 'mths_since_last_record:Missing',
     'mths_since_last_record:0-2',    'mths_since_last_record:3-20',
   'mths_since_last_record:21-31',   'mths_since_last_record:32-80',
   'mths_since_last_record:81-86',    'mths_since_last_record:>=86']
Length: 313, dtype: str

In [6]:
targets_test.value_counts()

good_bad
1           83112
0           10145
Name: count, dtype: int64

In [7]:
inputs_test.shape

(93257, 313)

In [8]:
inputs_test.columns.values

<StringArray>
[                    'Unnamed: 0',                             'id',
                      'member_id',                      'loan_amnt',
                    'funded_amnt',                'funded_amnt_inv',
                           'term',                       'int_rate',
                    'installment',                          'grade',
 ...
                  'dti:21.7-22.4',                    'dti:22.4-35',
                        'dti:>35', 'mths_since_last_record:Missing',
     'mths_since_last_record:0-2',    'mths_since_last_record:3-20',
   'mths_since_last_record:21-31',   'mths_since_last_record:32-80',
   'mths_since_last_record:81-86',    'mths_since_last_record:>=86']
Length: 313, dtype: str

In [9]:
features_all = ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:NM_VA',
'addr_state:NY',
'addr_state:OK_TN_MO_LA_MD_NC',
'addr_state:CA',
'addr_state:UT_KY_AZ_NJ',
'addr_state:AR_MI_PA_OH_MN',
'addr_state:RI_MA_DE_SD_IN',
'addr_state:GA_WA_OR',
'addr_state:WI_MT',
'addr_state:TX',
'addr_state:IL_CT',
'addr_state:KS_SC_CO_VT_AK_MS',
'addr_state:WV_NH_WY_DC_ME_ID',
'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',
'initial_list_status:f',
'initial_list_status:w',
'term:36',
'term:60',
'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',
'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',
'delinq_2yrs:0',
'delinq_2yrs:1-3',
'delinq_2yrs:>=4',
'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',
'open_acc:0',
'open_acc:1-3',
'open_acc:4-12',
'open_acc:13-17',
'open_acc:18-22',
'open_acc:23-25',
'open_acc:26-30',
'open_acc:>=31',
'pub_rec:0-2',
'pub_rec:3-4',
'pub_rec:>=5',
'total_acc:<=27',
'total_acc:28-51',
'total_acc:>=52',
'acc_now_delinq:0',
'acc_now_delinq:>=1',
'total_rev_hi_lim:<=5K',
'total_rev_hi_lim:5K-10K',
'total_rev_hi_lim:10K-20K',
'total_rev_hi_lim:20K-30K',
'total_rev_hi_lim:30K-40K',
'total_rev_hi_lim:40K-55K',
'total_rev_hi_lim:55K-95K',
'total_rev_hi_lim:>95K',
'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',
'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',
'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',
'mths_since_last_record:Missing',
'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>=86',
]

In [10]:
ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'delinq_2yrs:>=4',
'inq_last_6mths:>6',
'open_acc:0',
'pub_rec:0-2',
'total_acc:<=27',
'acc_now_delinq:0',
'total_rev_hi_lim:<=5K',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

In [11]:
inputs_train_ref_categories = inputs_train.loc[: ,features_all]
# we drop the variables with reference categories.
inputs_train_ref_categories = inputs_train_ref_categories.drop(ref_categories, axis = 1)
 
inputs_train_ref_categories.head()

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:NM_VA,addr_state:NY,...,mths_since_last_delinq:Missing,mths_since_last_delinq:4-30,mths_since_last_delinq:31-56,mths_since_last_delinq:>=57,mths_since_last_record:Missing,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>=86
221233,False,False,False,True,False,False,False,False,0,False,...,0,0,1,0,1,0,0,0,0,0
378461,False,False,False,True,False,False,False,True,0,False,...,1,0,0,0,1,0,0,0,0,0
117522,False,False,True,False,False,False,False,False,0,False,...,1,0,0,0,0,0,0,0,0,1
352107,False,False,False,True,False,False,False,True,0,False,...,0,1,0,0,1,0,0,0,0,0
253931,False,True,False,False,False,False,False,False,0,False,...,0,0,1,0,1,0,0,0,0,0

In [12]:
reg = LogisticRegression_with_p_values()

In [13]:
reg.fit(inputs_train_ref_categories, targets_train)

/private/tmp/claude-501/-Users-senayberhe-Documents/a205c631-6ae9-4dec-a24d-a104d161c6d7/scratchpad/crenv/lib/python3.12/site-packages/sklearn/utils/validation.py:1368: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [14]:
feature_name = inputs_train_ref_categories.columns.values
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
summary_table['Coefficients'] = np.transpose(reg.coef_)
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
# We take the result of the newly added method 'p_values'
p_values = reg.p_values
# Adding the intercept for completeness. We add the value 'NaN' in the beginning of the variable with p-values.
p_values = np.append(np.nan, np.array(p_values))
# Adding a new column, called 'p_values', containing the values from the 'p_values' variable.
summary_table['p_values'] = p_values

summary_table

                    Feature name  Coefficients      p_values
0                      Intercept      0.426351           NaN
1                        grade:A      0.225880  1.176434e-02
2                        grade:B      0.372168  4.412643e-10
3                        grade:C      0.333622  2.589324e-09
4                        grade:D      0.315507  4.947495e-09
..                           ...           ...           ...
93   mths_since_last_record:3-20      0.075202  6.037658e-01
94  mths_since_last_record:21-31      0.125163  3.667286e-01
95  mths_since_last_record:32-80      0.238192  3.918924e-02
96  mths_since_last_record:81-86     -0.031323  8.090321e-01
97   mths_since_last_record:>=86     -0.180532  1.155905e-01

[98 rows x 3 columns]

In [15]:
features_all = ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:NM_VA',
'addr_state:NY',
'addr_state:OK_TN_MO_LA_MD_NC',
'addr_state:CA',
'addr_state:UT_KY_AZ_NJ',
'addr_state:AR_MI_PA_OH_MN',
'addr_state:RI_MA_DE_SD_IN',
'addr_state:GA_WA_OR',
'addr_state:WI_MT',
'addr_state:TX',
'addr_state:IL_CT',
'addr_state:KS_SC_CO_VT_AK_MS',
'addr_state:WV_NH_WY_DC_ME_ID',
'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',
'initial_list_status:f',
'initial_list_status:w',
'term:36',
'term:60',
'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',
'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',
#'mths_since_earliest_cr_line:<140',
#'mths_since_earliest_cr_line:141-164',
#'mths_since_earliest_cr_line:165-247',
#'mths_since_earliest_cr_line:248-270',
#'mths_since_earliest_cr_line:271-352',
#'mths_since_earliest_cr_line:>352',
#'delinq_2yrs:0',
#'delinq_2yrs:1-3',
#'delinq_2yrs:>=4',
'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',
#'open_acc:0',
#'open_acc:1-3',
#'open_acc:4-12',
#'open_acc:13-17',
#'open_acc:18-22',
#'open_acc:23-25',
#'open_acc:26-30',
#'open_acc:>=31',
'pub_rec:0-2',
'pub_rec:3-4',
'pub_rec:>=5',
#'total_acc:<=27',
#'total_acc:28-51',
#'total_acc:>=52',
'acc_now_delinq:0',
'acc_now_delinq:>=1',
'total_rev_hi_lim:<=5K',
'total_rev_hi_lim:5K-10K',
'total_rev_hi_lim:10K-20K',
'total_rev_hi_lim:20K-30K',
'total_rev_hi_lim:30K-40K',
'total_rev_hi_lim:40K-55K',
'total_rev_hi_lim:55K-95K',
'total_rev_hi_lim:>95K',
'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',
'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',
#'mths_since_last_delinq:Missing',
#'mths_since_last_delinq:0-3',
#'mths_since_last_delinq:4-30',
#'mths_since_last_delinq:31-56',
#'mths_since_last_delinq:>=57',
#'mths_since_last_record:Missing',
#'mths_since_last_record:0-2',
#'mths_since_last_record:3-20',
#'mths_since_last_record:21-31',
#'mths_since_last_record:32-80',
#'mths_since_last_record:81-86',
#'mths_since_last_record:>=86',
]

In [16]:
ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'int_rate:>20.281',
#'mths_since_earliest_cr_line:<140',
#'delinq_2yrs:>=4',
'inq_last_6mths:>6',
#'open_acc:0',
'pub_rec:0-2',
#'total_acc:<=27',
'acc_now_delinq:0',
'total_rev_hi_lim:<=5K',
'annual_inc:<20K',
'dti:>35'
#'mths_since_last_delinq:0-3',
#'mths_since_last_record:0-2'
]

In [17]:
inputs_train_ref_categories = inputs_train.loc[: , features_all]

# we drop the variables with reference categories.
inputs_train_ref_categories = inputs_train_ref_categories.drop(ref_categories, axis = 1)
 
inputs_train_ref_categories.head()

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:NM_VA,addr_state:NY,...,annual_inc:>140K,dti:<=1.4,dti:1.4-3.5,dti:3.5-7.7,dti:7.7-10.5,dti:10.5-16.1,dti:16.1-20.3,dti:20.3-21.7,dti:21.7-22.4,dti:22.4-35
221233,False,False,False,True,False,False,False,False,0,False,...,0,0,0,0,1,0,0,0,0,0
378461,False,False,False,True,False,False,False,True,0,False,...,0,0,0,0,0,0,0,0,1,0
117522,False,False,True,False,False,False,False,False,0,False,...,0,0,0,0,1,0,0,0,0,0
352107,False,False,False,True,False,False,False,True,0,False,...,0,0,0,0,0,0,1,0,0,0
253931,False,True,False,False,False,False,False,False,0,False,...,0,0,0,0,0,1,0,0,0,0

In [18]:
inputs_train_ref_categories.shape

(373028, 71)

In [19]:
targets_train.shape

(373028, 1)

In [20]:
reg2 = LogisticRegression_with_p_values()
reg2.fit(inputs_train_ref_categories, targets_train)

/private/tmp/claude-501/-Users-senayberhe-Documents/a205c631-6ae9-4dec-a24d-a104d161c6d7/scratchpad/crenv/lib/python3.12/site-packages/sklearn/utils/validation.py:1368: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [21]:
feature_name = inputs_train_ref_categories.columns.values
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
summary_table['Coefficients'] = np.transpose(reg2.coef_)
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg2.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

# We add the 'p_values' here, just as we did before.
p_values = reg2.p_values
p_values = np.append(np.nan,np.array(p_values))
summary_table['p_values'] = p_values
summary_table

     Feature name  Coefficients      p_values
0       Intercept      0.243827           NaN
1         grade:A      0.178604  4.190104e-02
2         grade:B      0.311379  1.206974e-07
3         grade:C      0.292701  1.175080e-07
4         grade:D      0.291549  4.176863e-08
..            ...           ...           ...
67  dti:10.5-16.1     -0.015522  7.829464e-01
68  dti:16.1-20.3     -0.107770  5.611183e-02
69  dti:20.3-21.7     -0.131888  2.580603e-02
70  dti:21.7-22.4     -0.196489  1.873661e-03
71    dti:22.4-35     -0.175174  1.684361e-03

[72 rows x 3 columns]

In [22]:
# FIX: don't load ../models/pd_model.sav here — it holds the 84-feature model from
# credit_risk_model.ipynb and would overwrite the 71-feature reg2 fitted above.
# reg2 = joblib.load('../models/pd_model.sav')

In [23]:
#loading df with features refined.   
inputs_test_ref_categories = inputs_test.loc[: , features_all]

# we drop the variables with reference categories.
inputs_test_ref_categories = inputs_test_ref_categories.drop(ref_categories, axis = 1)
 
inputs_test_ref_categories.head()

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:NM_VA,addr_state:NY,...,annual_inc:>140K,dti:<=1.4,dti:1.4-3.5,dti:3.5-7.7,dti:7.7-10.5,dti:10.5-16.1,dti:16.1-20.3,dti:20.3-21.7,dti:21.7-22.4,dti:22.4-35
115315,False,True,False,False,False,False,False,True,0,True,...,1,0,0,1,0,0,0,0,0,0
420540,False,True,False,False,False,False,False,False,0,False,...,0,0,1,0,0,0,0,0,0,0
76957,False,True,False,False,False,False,False,True,0,False,...,0,0,0,0,0,1,0,0,0,0
114743,False,False,True,False,False,False,False,True,0,False,...,0,0,0,0,0,0,1,0,0,0
365207,True,False,False,False,False,False,False,True,0,False,...,1,0,0,0,0,0,0,0,1,0

In [24]:
# FIX: align the test set to the columns reg2 was trained on (not all 313 raw columns),
# and keep inputs_test intact instead of overwriting it.
inputs_test_aligned = inputs_test_ref_categories.reindex(
    columns=inputs_train_ref_categories.columns, fill_value=0).astype(float)

y_hat_test = reg2.model.predict(inputs_test_aligned.to_numpy())
y_hat_test_proba = reg2.model.predict_proba(inputs_test_aligned.to_numpy())[:, 1]
print(f'AUROC on the test set: {roc_auc_score(targets_test.values.ravel(), y_hat_test_proba):.3f}')

AUROC on the test set: 0.683